language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer update

script: phpunit -c test

notifications: 
  webhooks: http://monitor.koalamon.com/webhook/travis/?api_key=7EFA898C-5226-41A9-A260-6F78A7B85066
